image: gitpod/workspace-go
tasks:
  - init: go get
  - name: Start acceptance Test Environment
    command: make testacc-up
    openMode: split-right
# Port 8080 is used for acceptance testing, and we don't need to open it when the container comes up
ports:
  - port: 8080
    onOpen: ignore
vscode:
    extensions:
        - golang.Go