language: go

go:
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - master

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script:
        - go get github.com/golang/lint/golint
        - golint
    - stage: test
      script:
        - go test -v

matrix:
  allow_failures:
    - go: master
  fast_finish: true
